logic_dealer:
  listen_address: "127.0.0.1:18223"

logger:
  # 1. "info"
  # 2. "debug"
  # 3. "error"
  level: "debug"
  filepath: "/var/log/st_broker.log"
  listen_address: ":19093"

# broker的配置
broker:
  listen_address: ":18224"